projects/AccountTracker/AccountTracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'', include('main.urls', namespace="main")),
]

projects/AccountTracker/main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^list$', views.AccountList.as_view(), name='account_list'),
    url(r'^new$', views.AccountCreate.as_view(), name='account_new'),
    url(r'^edit/(?P<pk>\d+)$',
        views.AccountUpdate.as_view(), name='account_edit'),
    url(r'^delete/(?P<pk>\d+)$',
        views.AccountDelete.as_view(), name='account_delete'),
]

projects/AccountTracker/main/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.conf import settings

from localflavor.generic.models import IBANField


@python_2_unicode_compatible
class Account(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    iban_number = IBANField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)
    created_at.editable = True

    class Meta:
        verbose_name_plural = "accounts"

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('main:account_edit', kwargs={'pk': self.pk})

projects/AccountTracker/main/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import (LoginRequiredMixin)
from django.core.urlresolvers import reverse_lazy
from django.http import Http404
import datetime

from .models import Account


class ManipulationPermissionMixin(object):
    """
    Mixin to validate that only the author of
    instance of model:Account is allowed to edit
    or delete it.
    Author: Ahmed Etefy
    """

    def get_object(self, queryset=None):
        """
        Returns an instance of model:Account in the case that
        the author of the instance of model:Account is the
        the user logged in
        otherwise it raises a HTTP404 Error
        Author: Ahmed Etefy
        """
        obj = super(ManipulationPermissionMixin, self).get_object()
        if not obj.author == self.request.user:
            raise Http404("Permission Denied!")
        return obj


class AccountList(LoginRequiredMixin,
                  ListView):
    """
    View to display a list of instance of Model:Account
    Author: Ahmed Etefy
    """
    model = Account


class AccountCreate(LoginRequiredMixin,
                    CreateView):
    """
    View to create an instance of Model:Account with fields
    Account.first_name, Account.last_name, Account.iban_number.
    Author: Ahmed Etefy
    """
    model = Account
    fields = ['first_name', 'last_name', 'iban_number']
    success_url = reverse_lazy('main:account_list')

    def form_valid(self, form):
        """
        Function to set author of the Model:Account instance to
        be created as the currently authenticated User.
        """
        form.instance.author = self.request.user
        return super(AccountCreate, self).form_valid(form)


class AccountUpdate(LoginRequiredMixin,
                    ManipulationPermissionMixin,
                    UpdateView):
    """
    View to allow author of instance of Model:Account to update
    his instance of Model:Account with fields
    Account.first_name, Account.last_name, Account.iban_number.
    Author: Ahmed Etefy
    """
    model = Account
    fields = ['first_name', 'last_name', 'iban_number']
    success_url = reverse_lazy('main:account_list')

    def get_object(self, queryset=None):
        """
        Returns an instance of model:Account in the case that
        less than two hours from creation time had elapsed
        otherwise it raises a HTTP404 Error
        Author: Ahmed Etefy
        """
        obj = super(AccountUpdate, self).get_object()
        currentTime = datetime.datetime.now()
        creationTime = obj.created_at.replace(tzinfo=None)
        secDifference = (currentTime - creationTime).total_seconds()
        hourDifference = secDifference / 3600
        if hourDifference > 2:
            raise Http404("You can no longer edit this entry!")
        return obj


class AccountDelete(LoginRequiredMixin,
                    ManipulationPermissionMixin,
                    DeleteView):
    """
    View to allow author of instance of Model:Account to update
    his instance of Model:Account with fields
    Account.first_name, Account.last_name, Account.iban_number.
    Author: Ahmed Etefy
    """
    model = Account
    success_url = reverse_lazy('main:account_list')


class HomeView(TemplateView):
    """
    A home page view for the application
    Author: Ahmed Etefy
    """
    template_name = 'main/index.html'

projects/AccountTracker/main/templates/main/account_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}


<div class="container rounded mainContainerRounded centering">
	<div class="row">
        <div class="col-md-12">
        	<h2 class="centering">Delete Your Account</h2>  <br>
	        <form method="post">
			{% csrf_token %}
			     <h4> Are you sure you want to delete "{{ object }}" ? </h4> <br>
			    <div class="col-md-12">
			        <button type="submit" class="btn btn-primary btn-block addAccountBtn"><strong>SAVE</strong></button>
			        <a href="{% url 'main:account_list' %}"  class="btn btn-success btn-block addAccountBtn"><strong>BACK TO ACCOUNTS</strong></a>
			        <a  href="{% url 'auth:logout' %}?next={% url 'main:home' %}"><button type="button" class="btn btn-block btn-social btn-google centering" ><span type="button" class="fa fa-google"></span><strong>LOGOUT</strong></button> </a>
			    </div>
			</form>
        </div>
	</div>
</div>
{% endblock content %}

projects/AccountTracker/main/templates/main/account_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}


<div class="container rounded mainContainerRounded centering">
	<div class="row">
        <div class="col-md-12">
        	<h2 class="centering">Your Account</h2>  <br>
	        <form role="form" class="form" method="{% block form_method %}post{% endblock %}" enctype="multipart/form-data">
			    {% csrf_token %}
			    {% for field in form.visible_fields %}
			        <div class="col-md-12">
			            <div class="form-group">
			                <label class="control-label" for="{{ field.auto_id }}">{{ field.label }}</label>
			                {{ field | add_class:"form-control"}}
			                {% if field.errors %}
			                    <div class="control-label" for="inputError">
			                        {{ field.errors.as_text }}
			                    </div>
			                {% endif %}
			            </div>
			        </div>
			    {% endfor %}
			    {% for field in form.hidden_fields %}{{field}}{% endfor %}
			    <div class="col-md-12">
			        <button type="submit" class="btn btn-primary btn-block addAccountBtn"><strong>SAVE</strong></button>
			        <a href="{% url 'main:account_list' %}"  class="btn btn-success btn-block addAccountBtn"><strong>BACK TO ACCOUNTS</strong></a>
			        <a  href="{% url 'auth:logout' %}?next={% url 'main:home' %}"><button type="button" class="btn btn-block btn-social btn-google centering"><span type="button" class="fa fa-google"></span><strong>LOGOUT</strong></button> </a>
			    </div>
			</form>
			<!-- <div class="col-md-11"> -->
	        
	        <!-- </div> -->
        </div>
	</div>
</div>
{% endblock content %}

projects/AccountTracker/main/templates/main/account_list.html
{% extends 'base.html' %}
{% load static %}
{% block js %}
<script src="{% static 'js/bootstrap-notify.min.js' %}"></script>
<script type="text/javascript">
	$(document).ready(function(){
        $('.permission').click(function(){
        	$.notify({
              title: '<p><strong>Error</strong></p>',
              message: 'You are not authorized to manipulate this entry!'
          },{
              type: 'danger',
              z_index: 100000,
          });
         
        });
      });
</script>
{% endblock js %}

{% block content %}


<div class="container rounded mainContainerRounded">
	<div class="row">
        <div class="col-md-12">
	        <div class="table-responsive tableWhiteBackground">  
	        	<h2 class="centering" >Accounts</h2>  <br>
	            <table id="mytable" class="table table-bordred table-striped">
	            	{% if object_list %}   
	                <thead>  
	                    <th>First Name</th>
	                    <th>Last Name</th>
	                    <th>IBAN</th>
	                    <th>Edit</th> 
	                    <th>Delete</th>
	                </thead>
	                {% endif %}
	    			<tbody>
	    				{% for account in object_list %}
	    				<tr>
						    <td>{{ account.first_name }}</td>
						    <td>{{ account.last_name }}</td>
						    <td>{{ account.iban_number }}</td>
						    {% if account.author.id == request.user.id %}
							    <td><a href="{% url 'main:account_edit' account.id %}"><button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button></a></td>
                                <td><a href="{% url 'main:account_delete' account.id %}"><button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button></a></td>
                            {% else %}
                            	<td><button class="btn btn-primary btn-xs permission blackBtn"><span class="glyphicon glyphicon-lock"></span></button></td>
                                <td><button class="btn btn-primary btn-xs permission blackBtn" ><span class="glyphicon glyphicon-lock "></span></button></td>
						    {% endif %}
	    				</tr>
	    				{% empty %}
	    					<h2 class="centering">There are no registered accounts!</h2>  <br>
	    				{% endfor %}
	    			</tbody>
				</table>
				<div class="clearfix"></div>   
	        </div>
	        <a href="{% url 'main:account_new' %}"><button type="button" class="btn btn-primary btn-block addAccountBtn" ><strong>ADD NEW ACCOUNT</strong></button></a>
	        <a  href="{% url 'auth:logout' %}?next={% url 'main:home' %}"><button type="button" class="btn btn-block btn-social btn-google centering" ><span type="button" class="fa fa-google"></span><strong>LOGOUT</strong></button> </a>
        </div>
	</div>
</div>

{% endblock content %}

projects/AccountTracker/main/templates/main/base.html
{% load static %}
<!doctype html>
<html style="background: url({% static 'img/pw_maze_black_2X.png'%}) left top repeat;">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, maximum-scale=1">

<title>Homepage</title>
<link rel="icon" href="favicon.png" type="image/png">
<link rel="shortcut icon" href="favicon.ico" type="img/x-icon">

<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,800italic,700italic,600italic,400italic,300italic,800,700,600' rel='stylesheet' type='text/css'>

<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/animate.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/bootstrap-social.css' %}" rel="stylesheet" type="text/css">
{% block css %}
{% endblock css %}

<!--[if IE]><style type="text/css">.pie {behavior:url(PIE.htc);}</style><![endif]-->

<script type="text/javascript" src="{% static 'js/jquery.1.8.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
{% block js %}
{% endblock js %}

</head>
<body class="animated fadeInDown delay-07s img-rounded" style="margin: 5%">
{% block content %}
{% endblock content %}


</body>
</html>

projects/AccountTracker/main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<header class="header headerContainer" id="header"><!--header-start-->
	<div class="container">
    	<figure class="logo animated fadeInDown delay-07s">
        	<a href="#"><img src="{% static 'img/logo.png' %}" alt=""></a>	
        </figure>	
        <h1 class="animated fadeInDown delay-07s">Welcome To Account Tracker</h1>
        <ul class="we-create animated fadeInUp delay-1s">
        	<li>You are one stop away from managing your accounts. <br>Please login through your google account to start enjoying Account Tracker</li>
        </ul>
        {% if request.user.is_authenticated %}
        	<div class="link animated fadeInUp delay-1s buttonContainer" >
	            <a href="{% url 'main:account_list' %}" class="btn btn-block btn-primary viewAccountsButton"> VIEW ACCOUNTS
	            </a>
	            <a href="{% url 'auth:logout' %}?next={% url 'main:home' %}" class="btn btn-block btn-social btn-google googleButton">
	              <span type="button"  class="fa fa-google"></span> LOGOUT
	            </a>
	            
        	</div>
        {% else %}
        <div class="link animated fadeInUp delay-1s buttonContainer">
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-block btn-social btn-google googleButton" >
              <span type="button"  class="fa fa-google"></span> Log in with Google
            </a>
        </div>
        {% endif %}
    </div>
</header>
{% endblock content %}


